- fix in checking is netforking is up.
Changed files:
    qmail.init -> 1.4

diff --git a/qmail.init b/qmail.init
--- a/qmail.init
+++ b/qmail.init
@@ -18,7 +18,10 @@
 [ -f /etc/sysconfig/rwhod ] && . /etc/sysconfig/rwhod
 
 # Check that networking is up.
-[ "${NETWORKING}" = "no" ] && echo "Error: Networking is down" && exit 0
+if [ "${NETWORKING}" = "no" ]; then
+	echo "WARNING: Networking is down. Qmail service can't be runed."
+	exit 1
+fi
 
 
 # See how we were called.
